import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#030712",
  },
  screenDark: {
    backgroundColor: "#030712",
  },
  container: {
    padding: 20,
    paddingBottom: 120,
    gap: 18,
  },
  bottomTabBar: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 12,
    backgroundColor: "rgba(11, 17, 30, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 12,
    padding: 6,
    flexDirection: "row",
    gap: 6,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  bottomTabItem: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "transparent",
  },
  bottomTabItemActive: {
    backgroundColor: "rgba(224, 168, 76, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(224, 168, 76, 0.35)",
  },
  bottomTabText: {
    color: "#94A3B8",
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
    letterSpacing: 0.3,
  },
  bottomTabTextActive: {
    color: "#E0A84C",
    fontWeight: "700",
  },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#030712",
  },
  loadingTitle: {
    color: "#F8FAFC",
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  authScreen: {
    flex: 1,
    justifyContent: "center",
    padding: 24,
    backgroundColor: "#030712",
  },
  authScreenDark: {
    backgroundColor: "#030712",
  },
  authCard: {
    backgroundColor: "#0B111E",
    borderRadius: 12,
    padding: 28,
    borderWidth: 1,
    borderColor: "rgba(224, 168, 76, 0.28)",
    shadowColor: "#000",
    shadowOpacity: 0.45,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  authEyebrow: {
    color: "#E0A84C",
    fontSize: 12,
    letterSpacing: 1.5,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 10,
  },
  authTitle: {
    color: "#F8FAFC",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700",
    letterSpacing: -0.5,
    marginBottom: 10,
  },
  authText: {
    color: "#94A3B8",
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 20,
  },
  authInput: {
    backgroundColor: "#111C2E",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    color: "#F8FAFC",
    fontSize: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
  },
  authStatusText: {
    color: "#94A3B8",
    fontSize: 13,
    fontWeight: "600",
    marginTop: 12,
    textAlign: "center",
  },
  heroCard: {
    backgroundColor: "#0B111E",
    borderRadius: 12,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.09)",
    gap: 16,
    shadowColor: "#000000",
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 5,
  },
  pageHeader: {
    alignItems: "center",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  pageHeaderCompact: {
    alignItems: "stretch",
    flexDirection: "column",
    gap: 14,
    justifyContent: "flex-start",
  },
  pageHeaderTitle: {
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 30,
  },
  pageHeaderTitleCompact: {
    fontSize: 22,
    lineHeight: 28,
  },
  heroCopy: {
    gap: 8,
    flexShrink: 1,
    minWidth: 0,
  },
  heroCopyCompact: {
    width: "100%",
  },
  heroEyebrow: {
    color: "#94abc7",
    fontSize: 13,
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: "#f8fafc",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700",
  },
  heroText: {
    color: "#d7e3ef",
    fontSize: 15,
    lineHeight: 22,
  },
  heroActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  heroActionRowCompact: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 10,
    width: "100%",
  },
  statRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statCard: {
    flexGrow: 1,
    minWidth: 120,
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  statValue: {
    color: "#F8FAFC",
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -0.5,
    marginBottom: 4,
    fontVariant: ["tabular-nums"],
  },
  statLabel: {
    color: "#94A3B8",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  miniStat: {
    flexGrow: 1,
    minWidth: 90,
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  calculatorResultGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 6,
  },
  calculatorStat: {
    minWidth: 140,
    borderWidth: 1,
    borderColor: "rgba(224, 168, 76, 0.25)",
    backgroundColor: "#0B111E",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  miniStatValue: {
    color: "#F8FAFC",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: -0.3,
    marginBottom: 4,
    fontVariant: ["tabular-nums"],
  },
  miniStatLabel: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  // Canonical section header: title + actions share a row on wide screens and
  // wrap intentionally on narrow ones. The title keeps a 200px basis so it
  // can never be flex-crushed into per-character vertical stacking.
  sectionHeaderRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    rowGap: 8,
    columnGap: 12,
  },
  sectionHeaderTitle: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 200,
    minWidth: 0,
  },
  // Canonical wrapping action group. MUST take the full row (basis 100% +
  // minWidth 0): a wrapping container with basis auto keeps its single-line
  // max-content width and overflows instead of wrapping its own children.
  actionGroupWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    flexBasis: "100%",
    minWidth: 0,
  },
  panel: {
    backgroundColor: "#0B111E",
    borderRadius: 12,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  calculatorPanel: {
    backgroundColor: "#0B111E",
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  analyticsPanel: {
    backgroundColor: "#0B111E",
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  panelTitle: {
    color: "#F8FAFC",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 6,
    letterSpacing: -0.3,
  },
  panelSubtitle: {
    color: "#94A3B8",
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 16,
  },
  input: {
    backgroundColor: "#111C2E",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: "#F8FAFC",
    fontSize: 15,
    marginBottom: 12,
  },
  messageInput: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  notesInput: {
    minHeight: 120,
    textAlignVertical: "top",
  },
  inputLabel: {
    color: "#94a3b8",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 12,
  },
  optionChip: {
    backgroundColor: "#111C2E",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  optionChipActive: {
    backgroundColor: "rgba(224, 168, 76, 0.15)",
    borderColor: "rgba(224, 168, 76, 0.45)",
  },
  optionChipText: {
    color: "#94A3B8",
    fontWeight: "600",
    fontSize: 12,
  },
  optionChipTextActive: {
    color: "#E0A84C",
    fontWeight: "700",
  },
  broadcastStrip: {
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  broadcastStripText: {
    color: "#F8FAFC",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 10,
  },
  dualColumn: {
    gap: 18,
  },
  column: {
    flex: 1,
  },
  emptyState: {
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  emptyTitle: {
    color: "#F8FAFC",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 6,
  },
  emptyText: {
    color: "#94A3B8",
    fontSize: 13,
    lineHeight: 19,
  },
  clientRowShell: {
    flexDirection: "row",
    gap: 10,
    alignItems: "stretch",
    marginBottom: 8,
  },
  selectorPill: {
    // Compact multi-select control: a 78px pill here starved the client row
    // and stacked roster text vertically on tablet widths.
    width: 30,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111C2E",
    borderRadius: 6,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  selectorPillActive: {
    backgroundColor: "rgba(16, 185, 129, 0.2)",
    borderColor: "#10B981",
  },
  selectorPillText: {
    color: "#94A3B8",
    fontWeight: "700",
    fontSize: 12,
    textAlign: "center",
  },
  selectorPillTextActive: {
    color: "#10B981",
  },
  clientRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "#0B111E",
    gap: 12,
  },
  clientRowActive: {
    backgroundColor: "#111C2E",
    borderColor: "rgba(224, 168, 76, 0.35)",
  },
  clientRowMain: {
    flex: 1,
    gap: 4,
  },
  clientName: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "700",
  },
  clientMeta: {
    color: "#94a3b8",
    fontSize: 13,
  },
  clientSubMeta: {
    color: "#64748b",
    fontSize: 12,
  },
  dueBadge: {
    backgroundColor: "rgba(245, 158, 11, 0.18)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.4)",
  },
  dueBadgeText: {
    color: "#f59e0b",
    fontWeight: "700",
    fontSize: 12,
  },
  detailName: {
    color: "#f8fafc",
    fontSize: 26,
    fontWeight: "700",
    marginBottom: 6,
  },
  detailLine: {
    color: "#94a3b8",
    fontSize: 14,
    marginBottom: 4,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
    marginBottom: 12,
  },
  tag: {
    backgroundColor: "#111C2E",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  tagText: {
    color: "#CBD5E1",
    fontWeight: "600",
    fontSize: 12,
  },
  sectionLabel: {
    color: "#F8FAFC",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 14,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  detailBlock: {
    color: "#94A3B8",
    fontSize: 13,
    lineHeight: 20,
  },
  aiResearchResult: {
    gap: 12,
    marginTop: 12,
    padding: 16,
    backgroundColor: "#0B111E",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  aiResearchHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  sentimentPill: {
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  sentimentBullish: {
    backgroundColor: "rgba(16, 185, 129, 0.15)",
    color: "#10B981",
  },
  sentimentNeutral: {
    backgroundColor: "rgba(148, 163, 184, 0.15)",
    color: "#CBD5E1",
  },
  sentimentBearish: {
    backgroundColor: "rgba(244, 63, 94, 0.15)",
    color: "#F43F5E",
  },
  darkChip: {
    backgroundColor: "#2563EB",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  darkChipText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 13,
  },
  lightChip: {
    backgroundColor: "#111C2E",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  lightChipText: {
    color: "#CBD5E1",
    fontWeight: "600",
    fontSize: 13,
  },
  inlineActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 10,
  },
  linkButton: {
    paddingVertical: 8,
  },
  linkButtonText: {
    color: "#38BDF8",
    fontWeight: "700",
  },
  linkDanger: {
    color: "#F43F5E",
  },
  historyItem: {
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 12,
    color: "#CBD5E1",
    marginTop: 8,
    lineHeight: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  reportBlock: {
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 14,
    color: "#CBD5E1",
    lineHeight: 21,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  reminderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  slimButton: {
    backgroundColor: "#111C2E",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  slimButtonText: {
    color: "#F8FAFC",
    fontWeight: "700",
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  categoryCard: {
    width: "47%",
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  analyticsSummaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 8,
    marginBottom: 18,
  },
  analyticsMetricCard: {
    flexGrow: 1,
    minWidth: 140,
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  analyticsBlue: {
    backgroundColor: "rgba(37, 99, 235, 0.08)",
    borderColor: "rgba(59, 130, 246, 0.28)",
  },
  analyticsSlate: {
    backgroundColor: "#0B111E",
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  analyticsGreen: {
    backgroundColor: "rgba(16, 185, 129, 0.08)",
    borderColor: "rgba(16, 185, 129, 0.28)",
  },
  analyticsRed: {
    backgroundColor: "rgba(244, 63, 94, 0.08)",
    borderColor: "rgba(244, 63, 94, 0.28)",
  },
  analyticsGold: {
    backgroundColor: "rgba(224, 168, 76, 0.08)",
    borderColor: "rgba(224, 168, 76, 0.28)",
  },
  analyticsMetricLabel: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  analyticsMetricValue: {
    color: "#F8FAFC",
    fontSize: 22,
    fontWeight: "700",
    letterSpacing: -0.5,
    fontVariant: ["tabular-nums"],
  },
  allocationRow: {
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    marginTop: 10,
  },
  allocationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  allocationBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#111C2E",
    overflow: "hidden",
    marginBottom: 8,
  },
  allocationBarFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#3B82F6",
  },
  analyticsAlert: {
    backgroundColor: "rgba(245, 158, 11, 0.12)",
    borderRadius: 8,
    padding: 12,
    color: "#F59E0B",
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.28)",
    lineHeight: 20,
    marginTop: 8,
  },
  analyticsListCard: {
    backgroundColor: "#0B111E",
    borderRadius: 8,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    marginTop: 10,
  },
  analyticsPositive: {
    color: "#10B981",
    fontWeight: "700",
    marginTop: 6,
  },
  analyticsNegative: {
    color: "#EF4444",
    fontWeight: "700",
    marginTop: 6,
  },
  categoryValue: {
    color: "#F8FAFC",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 4,
  },
  categoryLabel: {
    color: "#94A3B8",
    fontSize: 13,
  },
  holdingCard: {
    backgroundColor: "#0B111E",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    padding: 16,
    marginTop: 12,
  },
  holdingTitle: {
    color: "#F8FAFC",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 6,
  },
  holdingMeta: {
    color: "#94A3B8",
    fontSize: 13,
    marginBottom: 4,
  },
  holdingNote: {
    color: "#64748B",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
  },
  settingsOverviewPanel: {
    backgroundColor: "#0B111E",
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  settingsStatusGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  settingsStatusItem: {
    backgroundColor: "#111C2E",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 8,
    borderWidth: 1,
    flexGrow: 1,
    flexBasis: 150,
    padding: 12,
  },
  settingsStatusLabel: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 5,
    textTransform: "uppercase",
  },
  settingsStatusValue: {
    color: "#F8FAFC",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 19,
  },
  settingsSectionTitle: {
    color: "#F8FAFC",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 10,
  },
  settingsRow: {
    alignItems: "center",
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 16,
    justifyContent: "space-between",
    paddingVertical: 14,
  },
  settingsActionRow: {
    alignItems: "center",
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 16,
    justifyContent: "space-between",
    paddingVertical: 14,
  },
  settingsActionText: {
    color: "#E0A84C",
    fontSize: 14,
    fontWeight: "700",
  },
  settingsButtonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
  },
  toggleCopy: {
    flex: 1,
  },
  toggleTitle: {
    color: "#F8FAFC",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  toggleText: {
    color: "#94A3B8",
    fontSize: 13,
    lineHeight: 19,
  },
  primaryButton: {
    backgroundColor: "#2563EB",
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2563EB",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.2,
  },
  goldButton: {
    alignSelf: "flex-start",
    backgroundColor: "#E0A84C",
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  goldButtonText: {
    color: "#030712",
    fontWeight: "800",
    fontSize: 14,
  },
  secondaryButton: {
    backgroundColor: "#111C2E",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  secondaryButtonCompact: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    minHeight: 44,
    minWidth: 0,
  },
  secondaryButtonText: {
    color: "#CBD5E1",
    fontWeight: "600",
    fontSize: 13,
  },
  logoutButton: {
    borderWidth: 1,
    borderColor: "rgba(244, 63, 94, 0.35)",
    backgroundColor: "rgba(244, 63, 94, 0.1)",
  },
  logoutButtonText: {
    color: "#F43F5E",
    fontWeight: "700",
  },
  secondaryAction: {
    marginTop: 14,
    alignSelf: "center",
  },
  secondaryActionText: {
    color: "#38BDF8",
    fontWeight: "700",
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
  },
  modalBackdropCenter: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    maxHeight: "90%",
    backgroundColor: "#0D1524",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  modalCardCenter: {
    width: "100%",
    maxWidth: 580,
    maxHeight: "85%",
    borderRadius: 12,
    backgroundColor: "#0D1524",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderColor: "rgba(224, 168, 76, 0.25)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.55,
    shadowRadius: 40,
    elevation: 20,
  },
  modalTitle: {
    color: "#F8FAFC",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 10,
  },
  modalSecondary: {
    flex: 1,
    backgroundColor: "#111C2E",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    paddingVertical: 12,
    alignItems: "center",
  },
  modalSecondaryText: {
    color: "#CBD5E1",
    fontWeight: "700",
  },
  clientDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 14,
  },
  clientListAvatar: {
    width: 38,
    height: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(224, 168, 76, 0.35)",
  },
  clientListAvatarPlaceholder: {
    width: 38,
    height: 38,
    borderRadius: 999,
    backgroundColor: "rgba(224, 168, 76, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(224, 168, 76, 0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  clientListAvatarText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#E0A84C",
  },
  clientDetailAvatar: {
    width: 52,
    height: 52,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#E0A84C",
  },
  clientDetailAvatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 999,
    backgroundColor: "rgba(224, 168, 76, 0.15)",
    borderWidth: 2,
    borderColor: "#E0A84C",
    alignItems: "center",
    justifyContent: "center",
  },
  clientDetailAvatarText: {
    fontSize: 18,
    fontWeight: "800",
    color: "#E0A84C",
  },
});

export const appStyles = styles;
export type AppStyles = typeof styles;
